services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: string_analysis-api
    ports:
      - "${PORT:-8000}:8000"
    environment:
      HOST: "0.0.0.0"
      PORT: "8000"
      RELOAD: "false"
      MAX_STRING_LENGTH: 400
      LOG_LEVEL: "INFO"
    restart: unless-stopped
    volumes:
      - ./app:/app/app:ro